### ISSUE TITLE
FID between a dataset and a single sample

### ISSUE THREAD

**Issue by caesar-one** [hukkelas/pytorch-frechet-inception-distance#1]
Is there a way to calculate the Frechet Inception Distance between a dataset and just one sample (instead of a set of them), producing consistent results?

**Comment by hukkelas** [comment]
Not possible.
FID measures the distance between two distributions, where the each of the distributions are approximated from a set of real examples, and a set of fake examples.

Also, this repository is deprecated. Use:https://github.com/mseitzer/pytorch-fid instead.

Finally, the LPIPS metric could be more useful for image-to-image similarity.

**Comment by caesar-one** [comment]
Thank you very much for your answer. Actually, our idea is to calculate the FID distance between the two estimated Gaussian distributions and only at a later stage to see how likely specific samples are with respect to these distributions. If the FID distance is high - the two distributions are closed - it may be of some interest to give a score to each sample in terms of coherence with the observed phenomenon probability density.
