### ISSUE TITLE
first_image shape is inverted in load_image function

### ISSUE THREAD

**Issue by muneeb2001** [hukkelas/pytorch-frechet-inception-distance#2]
ERROR
``Traceback (most recent call last):``
``File "fid.py", line 280, in <module>``
``    images1 = load_images(options.path1)``
``  File "fid.py", line 251, in load_images``
``    final_images[idx] = im``
``ValueError: could not broadcast input array from shape (128,96,3) into shape (96,128,3)``

This occurs because at line 242 ``W, H = first_image.shape[:2] ``  **height and width dimensions** are switched.

**Comment by KomputerMaster64** [comment]
Thank you for the solution

**Comment by hukkelas** [comment]
This repository is deprecated and I recommend you to use torch fidelity instead: https://github.com/toshas/torch-fidelity
