### ISSUE TITLE
Query: WGAN-GP FID SCORE (PyTorch)

### ISSUE THREAD

**Issue by KomputerMaster64** [hukkelas/pytorch-frechet-inception-distance#4]
Thank you for sharing the implementations of the GAN based models on popular datasets like CelebA.
I have implemented the WGAN-GP model (in PyTorch), the samples are looking closer the reported work (please refer to the attached image). When I try to evaluate the Fréchet inception distance (FID score), I am not able to comprehend the high values of 100+ (best value 113.4). Others have reported lower FID Scores. Authors in the [Quality Aware Generative Adversarial Networks](https://arxiv.org/abs/1911.03149) compared the vairous FID scores for various GAN models and there [Ishaan Gulrajani's official implementation of WGAN-GP](https://github.com/igul222/improved_wgan_training) got FID score of 12.89.

I request you to guide me.
Regards
Prabhav

I have used the following repositories for reference while implementing the WGAN-GP model and evaluating the FID scores:
[LynnHo](https://github.com/LynnHo)/[DCGAN-LSGAN-WGAN-GP-DRAGAN-Pytorch](https://github.com/LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Pytorch)
[CharlesNord](https://github.com/CharlesNord)/[WGAN-GP-DRAGAN-Celeba-Pytorch](https://github.com/CharlesNord/WGAN-GP-DRAGAN-Celeba-Pytorch)
[eriklindernoren](https://github.com/eriklindernoren)/[PyTorch-GAN](https://github.com/eriklindernoren/PyTorch-GAN)
[hukkelas](https://github.com/hukkelas)/[pytorch-frechet-inception-distance](https://github.com/hukkelas/pytorch-frechet-inception-distance)
[mseitzer](https://github.com/mseitzer)/[pytorch-fid](https://github.com/mseitzer/pytorch-fid)

**Comment by hukkelas** [comment]
Hi.

This repository is deprecated and I recommend you to use torch_fidelity instead. https://github.com/toshas/torch-fidelity

**Comment by KomputerMaster64** [comment]
Thank you for sharing the implementation of the FID and IS scores.
I wanted to use the code to find the metrics for the samples generated by a GAN model trained on the CelebA dataset as well as the dataset with transformations (custom version of CelebA dataset), thereby I thought of using `input1` and `input2`. However when I use the command

```
fidelity --gpu 0 --fid --input1 /images/sample_dir/ --input2 /images/CelebA_DATASET
```

<br>
I am getting the following error (which suggests to use given datasets only)

```
ValueError: Input descriptor "input" field can be either an instance of Dataset, GenerativeModelBase class, or a string, such as a path to a name of a registered dataset (cifar10-train, cifar10-val, stl10-train, stl10-test, stl10-unlabeled), a directory with file samples, or a path to an ONNX or PTH (JIT) module
```
<br>I request you to guide me in this regard.
<br>Kind regards
<br>Prabhav

**Comment by hukkelas** [comment]
Please file the issue in the torch fidelity repository, as I'm sure the torch-fidelity developers are better suited to answer your question.
